### ISSUE TITLE
Error in minifb v0.17.0 dependency

### ISSUE THREAD

**Issue by diego-crespo** [redox-os/orbtk#439]
**Describe the bug**
Compilation fails for building the minimal example of OrbTk due to an error in minifb v.17. This appears to be fixed [in version .19 of minfb wayland](https://github.com/emoon/rust_minifb/blob/master/src/os/posix/wayland.rs), and [ x11.rs
](https://github.com/emoon/rust_minifb/blob/master/src/os/posix/x11.rs)
> error[E0599]: no variant or associated item named `XKB_KEYMAP_FORMAT_TEXT_v1` found for enum `xkb_keymap_format` in the current scope
    --> /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/minifb-0.17.0/src/os/posix/wayland.rs:1056:59
     |
1056 |                         xkbcommon_sys::xkb_keymap_format::XKB_KEYMAP_FORMAT_TEXT_v1,
     |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^
     |                                                           |
     |                                                           variant or associated item not found in `xkb_keymap_format`
     |                                                           help: there is a variant with a similar name (notice the capitalization): `XKB_KEYMAP_FORMAT_TEXT_V1`

> error[E0308]: mismatched types
   --> /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/minifb-0.17.0/src/os/posix/x11.rs:423:52
    |
423 |                     (d.lib.XInternAtom)(d.display, "_MOTIF_WM_HINTS\0" as *const _ as *const i8, 0);
    |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

I believe this can be fixed by bumping the version used by OrbTk.

**To Reproduce**
1. Run cargo build using orbtk version 0.3.1-alpha3 with the minimal example.

**Desktop (please complete the following information):**
 Raspberry Pi 4 8gb running Raspbian OS

**Comment by CyanBlob** [comment]
Were you able to find a fix? I have the same problem

**Comment by diego-crespo** [comment]
@CyanBlob Unfortunately I was not. I tried just using the dev branch in the Cargo.toml to see if there was a fix in the latest version
`orbtk = { git = "https://github.com/redox-os/orbtk.git", branch = "develop" }
`
but I ended up running into different errors which I was not able to resolve. I don't have the Rust skills to investigate any further

**Comment by vioulo** [comment]
Same with me :disappointed: 
![image](https://user-images.githubusercontent.com/27475937/116358963-d1ff5400-a830-11eb-86c0-eadb4ce5e213.png)

**Comment by ghost** [comment]
The minifb support will be dropped with the next release.

**Comment by funkydatascience** [comment]
change XKB_KEYMAP_FORMAT_TEXT_v1 to XKB_KEYMAP_FORMAT_TEXT_V1

**Comment by funkydatascience** [comment]
related to https://github.com/emoon/rust_minifb/pull/233
